name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./CashSavvy
      run: dotnet restore
    - name: Build
      working-directory: ./CashSavvy
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./CashSavvy
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      working-directory: ./CashSavvy
      run: dotnet publish --no-restore -c Release -o ./publish
      
    - name: Build and Publish container
      uses: TCPShield/gp-docker-action@1.1.13
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: cash-savvy
